MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './weights_pretrained/jx_vit_base_p16_224-80ecf9dd.pth'
  # PRETRAIN_PATH: './logs/market_vit_base/vit_transformer_resume_110.pth'
  NAME: 'vit_transformer'
  TRANSFORMER:
    TYPE: 'vit_base_patch16_224_TransReID'
  

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  FEATURE_DIMENSION: 2048
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  # decay rate of learning rate
  # GAMMA: 0.1
  # WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

LOSS:
  ID_LOSS_TYPE: 'cross_entropy'
  ID_LOSS_OUTPUT_INDEX: 0
  METRIC_LOSS_OUTPUT_INDEX: 1
  COMPONENTS: [
    {"type": "cross_entropy", "weight": 1.0, "output_index": 0, "label_smooth": "off"},
    {"type": "triplet", "weight": 1.0, "output_index": 1, "margin": None},
  ]

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  # PIXEL_MEAN: [0.485, 0.456, 0.406]
  # PIXEL_STD: [0.229, 0.224, 0.225]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PADDING: 10
  TRAIN_KEYS: [0, 1, 2, 3]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  TRAIN_TRANSFORMS: [
    {'transform':'resize'},
    {'transform':'random_horizontal_flip', 'prob': 0.5},
    {'transform':'pad', 'padding': 10}, 
    {'transform':'random_crop'}, 
    {'transform':'to_tensor'}, 
    {'transform':'normalize'}, 
    {'transform':'random_erasing', 'prob': 0.5}    
    ]

  TEST_TRANSFORMS: [
      {'transform':'resize'},
      {'transform':'to_tensor'},
      {'transform':'normalize'}, 
      ]

DATASETS:
  NAMES: market1501
  DIR: 'market1501'

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  # WEIGHT: './logs/market_vit_base/vit_transformer_resume_120.pth'
  WEIGHT: 'D:/work/ReID_projects/ReIdPrototype/logs/market_vit_base/vit_transformer_model_full.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

LOGGING: 
  WANDB_USE: False
  WANDB_PROJECT: 'transformer_vit_market_base'
  WANDB_NAME: 'market_vit_base'
OUTPUT_DIR: './logs/market_vit_base_test'
# EXPERIMENT_NAME: 'vit_base_market_norm_imgnet_close'
EXPERIMENT_NAME: 'vit_base_market'

