TRAINING_LOG_CSV = 'training_log_{}.csv'
VALIDATION_LOG_CSV = 'validation_log_{}.csv'

VIT_BASE_HIDDEN_SIZE = 768
VIT_BASE_HEADS = 12
VIT_BASE_LAYERS = 12

VIT_SMALL_HEADS = 8
VIT_SMALL_LAYERS = 8

VIT_PATCH_SIZE = 16

DEIT_HEADS = 6
DEIT_LAYERS = 12

DEFAULT_INPUT_CHANNELS = 3

# Dataset
IMG_INDEX = 0
PID_INDEX = 1
CAMID_INDEX = 2
TRACKID_INDEX = 3
PATH_INDEX = 4
